### ISSUE TITLE
Difficult to debug due to dist being minified

### ISSUE THREAD

**Issue by pbeshai** [gabrielflorit/blockup#21]
Probably unnecessary to even bother minifying for a block anyway, but would be nice to have option to make it not minify the output.

**Comment by pbeshai** [comment]
At least during development, Chrome supports most of the ES2015 features already, so to workaround this you can temporarily edit index.html to link `script.js` instead of `dist.js`.

**Comment by gabrielflorit** [comment]
Ah I see. I minify so readers won't be confused about the existence of two `.js` files. I suppose we could always enable sourcemaps? But then you'd have to remember to not version it.

**Comment by pbeshai** [comment]
Yea, after seeing it deployed, it's nice to be minified so it is ignored.
Inline source maps may be a good solution.

**Comment by gabrielflorit** [comment]
Closed by https://github.com/gabrielflorit/blockup/pull/23
