### ISSUE TITLE
Would be nice if warned about missing preview and thumbnail images

### ISSUE THREAD

**Issue by pbeshai** [gabrielflorit/blockup#22]
From the [blocks docs](http://bl.ocks.org/-/about):

> To add a thumbnail preview, add a 230×120 thumbnail.png to your Gist. For social media, you can also add a larger 960×500 preview.png or preview.jpg.

Maybe a warning on start-up that says:

```
Warning: Did not find thumbnail.png. Expected a 230×120 image.
Warning: Did not find preview.png or preview.jpg. Expected a 960×500 image.
```

This way it reminds you to add the image _and_ what the expected size of them is.

**Comment by gabrielflorit** [comment]
Hmm interesting. On the one hand, I have a feeling it might be confusing to see this warning right away when you create a new block - "what did I do? I just created a new one! where did I mess up?"

On the other hand, it's quite nice to see the warning WITH the expected dimensions, I always forget.

Is there another way we could do this so that the user doesn't get a warning on start?

**Comment by gabrielflorit** [comment]
Maybe when you stop it? Is there a way to detect killing the gulp process?

**Comment by pbeshai** [comment]
hmm yea I know, it's not ideal to immediately show that after generating a new block. It might be confusing to see it on exit, although there are probably ways to hook into the exiting cleanup to do it.

Might be nice if you could do:
- `blockup check` - validate your block
- `blockup publish <title>` - run `blockup check` then use `gistup --description <title>` to publish it.

**Comment by gabrielflorit** [comment]
The `blockup publish` idea is interesting - but is that making this little tool do too much? Or maybe not, maybe it's a useful addition? I don't know.

**Comment by pbeshai** [comment]
I think it's reasonable personally to include it. I had to go download gistup and then figure out how to use it and I didn't set a description so my block had a hash as a title which took a while to figure out. If you're interested, I can take a stab at it and you can decide whether or not you want to include it. I'd just make gistup a dependency and call it after checking for files and warning if they're missing/possibly aborting if user says to.

**Comment by gabrielflorit** [comment]
I think this approach makes sense - I can anticipate others being confused when it comes to uploading the gist. A PR would be very welcome!

**Comment by gabrielflorit** [comment]
Something that came to mind: what do you think of using the same command, `blockup publish`, to either 1) create and push to gist if current dir isn't a git repo, or 2) if current dir is a repo, tell user "please use git to publish the latest changes"?

**Comment by pbeshai** [comment]
+1 good idea, prevents errors and guides to correct behaviour.

**Comment by pbeshai** [comment]
I've updated the PR #24 to include these ideas. See https://github.com/gabrielflorit/blockup/pull/24#issuecomment-254021765

**Comment by gabrielflorit** [comment]
BTW @pbeshai this works beautifully. Thanks again.

**Comment by pbeshai** [comment]
Awesome! glad to hear it =]
